### PR TITLE
Created Logo Designs 

### PR DESCRIPTION
**Pull request by Sabihashaik**
Ref #215 

I've created drafts for 2 logo designs.
Design 1 drawing Design 2drawing

I utilized icons from flaticon.com, the [licensing document](https://file000.flaticon.com/downloads/license/license.pdf)  allows altering and using the icons as long as appropriate attribution is provided.

Icons Utilized:

- [Cloud ](https://www.flaticon.com/free-icon/cloud_1163624#term=cloud&page=1&position=3)
- [Server](https://www.flaticon.com/free-icon/server_148820#term=server&page=1&position=11)
- [Connection](https://www.flaticon.com/free-icon/web_1508791#term=database&page=1&position=46)

I did not use the logos for PostgreSQL or Microsoft SQL Server due to copyright reasons.  Please let me know any feedback or if you had a different vision for the logo!

### CODE REVIEW

**Comment by GeoffMontee** [comment]
Thanks for the contribution!

> I did not use the logos for PostgreSQL or Microsoft SQL Server due to copyright reasons.

I think it is probably OK to use the PostgreSQL name and/or logo. See [here](https://www.postgresql.org/about/policies/trademarks/):

> The following are examples of acceptable uses of the logo:
> 
> * Inclusion of the name(s) or logo on your website offering PostgreSQL support or consultancy services.
> * Inclusion of the name(s) or logo on your website from which you offer PostgreSQL-related or PostgreSQL-derived software products.
> * Inclusion of a modified version of the logo on a PostgreSQL user forum that you run.
> * Inclusion of the name(s) or logo in your software or documentation to indicate that it runs on or with PostgreSQL.
> * Use of the name(s) or logo on websites, publications or merchandise, modified or unmodified, for PostgreSQL user groups, events, or non-profit organizations which support PostgreSQL.
> * Use of the name(s) or logo to advertise PostgreSQL-related content in a public event.
> * Use of the name(s) or logo in news articles or blogs which reference the PostgreSQL Project or database system.

The logo for `tds_fdw` would fall under this category:

> * Inclusion of the name(s) or logo in your software or documentation to indicate that it runs on or with PostgreSQL.

I have some suggestions for the logo that are loosely based on the ones that you created here. However, before I do, I just want to mention a disclaimer that I am no expert in branding, marketing, or graphic design, so I can't claim that my ideas are the best way to go. I am definitely open to suggestions.

Regardless, what do you say about something like this?:

* We have two or more of the server icons. i.e.:
** [server](https://www.flaticon.com/free-icon/server_148820)
* We connect the server icons with some kind of network connection icon.
** [network connection](https://www.flaticon.com/free-icon/network_2180829)
* We put the PostgreSQL elephant logo on one of the server icons. This would represent that the server is a PostgreSQL Server.
** [PostgreSQL Slonik elephant logo](https://wiki.postgresql.org/wiki/Logo)
* We put a speech bubble of some kind on the remaining server icons. Inside the speech bubble, it should contain the text "TDS". This would represent that the server is speaking the [Tabular Data Stream (TDS) protocol](https://en.wikipedia.org/wiki/Tabular_Data_Stream). This is the protocol spoken by Microsoft SQL Server and Sybase servers.
** [speech bubble](https://www.flaticon.com/free-icon/conversation_1246332)

How does that sound?

**Comment by Sabihashaik** [comment]
@GeoffMontee Great Ideas!
I've tried a few variations below
Design 3 drawing 
Design 4drawing
Design 5 drawing

Let me know your feedback. I liked Design 3 but maybe I can make all the colors used similar to the PostgreSQL Colors?

**Comment by GeoffMontee** [comment]
Nice work! I also like design 3.

@juliogonzalez , do you have any thoughts?

**Comment by juliogonzalez** [comment]
I like design 3 as well :-)

My only concern is: can we get another variant for such design what can be used as icon an avatar?

Right now would look like this way:

image

And if possible as SVG or some format that can we can scale without loosing quality.

**Comment by Sabihashaik** [comment]
@juliogonzalez Sure, SVG is possible. Do you have any suggestions in mind for the Avatar Icon?

**Comment by juliogonzalez** [comment]
I am not designer (so I hope you will excuse my ugly examples :-)) but I'd propose keeping the design number 3, but having all the icons closer.

Something like this:

68747470733a2f2f692e696d6775722e636f6d2f57766a346c696b2e706e67

As 88x88 would look like this:

avatar

(Sorry, it's ugly as it's a resized png :-))

**Comment by juliogonzalez** [comment]
@Sabihashaik ping? :-)

**Comment by Sabihashaik** [comment]
Hi @juliogonzalez, sorry got caught up in a little bit of work. Will send across a PR by tomorrow! Hope that's okay  😄

**Comment by Sabihashaik** [comment]
Sorry about the delay, [here](https://drive.google.com/drive/folders/1mfSsfRHy9J6VyV6nWmnN4DK4YAA6hlP-?usp=sharing) are the updated files. I have a transparent and a non-transparent PNG uploaded.
I've also added an SVG version of the file.

**Comment by juliogonzalez** [comment]
The black and white looks good, but is it just me or the color SVG is not really a SVG with paths (such as black and white) but just images inside a SVG?

Not even with Inkscape I can resize properly, as the image pixelates, and it seems there are only three paths, the `TDS` signs are one path each, and the rest of the image is the other path.

**Comment by juliogonzalez** [comment]
This is what I mean:
image

**Comment by Sabihashaik** [comment]
Oh I see, Let me tweak it a bit and see if I can fix this.

**Comment by juliogonzalez** [comment]
Ping @Sabihashaik any news? :-)

**Comment by RAFAELDEV2016** [comment]
Hi,

Please see pull request #274 

I have turned the SVG version of the logo prepared by Sabihashaik into a true vector SVG version of the logo.
I have put the file into a new floder named "logo".
I have included the logo into the README.MD file.

I hope it will suit you.

Best regards

**Comment by RAFAELDEV2016** [comment]
Ping @juliogonzalez could you please have a look at pull request #274 and tell me if you can approve and merge please ?

**Comment by juliogonzalez** [comment]
#274 is now merged, so let's close this one.

Thanks a lot for the contributions @Sabihashaik and @RAFAELDEV2016!

**Comment by GeoffMontee** [comment]
Hi @Sabihashaik and @RAFAELDEV2016,

Thanks for the contributions!

The logo from #274 has been added to the GitHub organization:

https://github.com/tds-fdw

**Pull request closed without merging**
