### PR TITLE
postgresql 15 support

### PR DESCRIPTION
**Pull request by hellower**
postgresql 15 support

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Adding now PostgreSQL15 to the CI, so we can run it.

**Comment by GeoffMontee** [comment]
Thanks for updating the CI, @juliogonzalez !

**Comment by juliogonzalez** [comment]
CI is ready, and validated at https://jenkins.juliogonzalez.es/job/tds_fdw-build-free/33/ so time for the magic sentence:

Test this, please

**Comment by juliogonzalez** [comment]
@GeoffMontee ready for you to merge.

You may want to prepare a release as well :-)

**Comment by GeoffMontee** [comment]
This has been merged.

Thanks for the PR, @hellower !

**Comment by GeoffMontee** [comment]
> You may want to prepare a release as well :-)

Good idea. It has been a while since I have worked on tds_fdw, so I will need to setup a development environment before I can do that. I created issue #316 to track that.

**Pull request merged**
