### PR TITLE
Replace all double-colon casting with CAST(...as )

### PR DESCRIPTION
**Pull request by bikethis81**
Hi Geoff,

I just searched for "::" in deparse.c and replaced all remaining instances with the appropriate MS SQL server syntax for use in the CAST(...as ..) form that was begun earlier.

This fixes a few things, notably complex joins, where the printRemotePlaceholder method is called.

All my queries work with the patched code. YMMV.

Thank you so much for your work on this!

-Shane

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Test this, please

**Comment by juliogonzalez** [comment]
Test this please

**Comment by bikethis81** [comment]
Couldn't get the tests to pass "connect() got an unexpected keyword argument 'server'" in the mssql-tests.py Glad you got it to work Jenkins!

**Comment by GeoffMontee** [comment]
Thanks a lot for the patch, @bikethis81! It has been merged.

**Pull request merged**
