### PR TITLE
Fix importing from Sybase schema (float fields)

### PR DESCRIPTION
**Pull request by vitalca**
Related issue: #321

### CODE REVIEW

**Comment by GeoffMontee** [comment]
Test this, please

**Comment by juliogonzalez** [comment]
As this is old, let's test again.

Test this, please

**Comment by GeoffMontee** [comment]
Hi @vitalca,

Thanks for the PR. Sorry for letting this one sit for a while, too. Let's make sure that it still passes the tests run by jenkins.

Test this, please

**Comment by GeoffMontee** [comment]
This has been merged. Thanks for the PR!

**Pull request merged**
