### PR TITLE
Extend Import Foreign Schema to Views

### PR DESCRIPTION
**Pull request by pgssimon**
From Feature Request #178

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@jenkins-juliogonzalez test this, please

This will see if current tests are not failing, can you add tests to check that feature works? It's important not only to validate this PR, but also to validate that future PRs don't break the feature.

**Comment by juliogonzalez** [comment]
@pgssimon can you add the tests to import a view?

**Comment by pgssimon** [comment]
Just a bit pushed for time currently, will try to add test this week or next.

**Comment by thomasfedb** [comment]
Very keen for this change, the MSSQL databases we work with are almost entirely views

**Comment by juliogonzalez** [comment]
@pgssimon any news? :-)

**Comment by juliogonzalez** [comment]
BTW: There's a readme now about the tests: https://github.com/tds-fdw/tds_fdw/blob/master/tests/README.md :-)

**Comment by juliogonzalez** [comment]
Superseded by #248

**Comment by GeoffMontee** [comment]
#248 was just merged. Sorry for the delay!

**Pull request closed without merging**
