### PR TITLE
Implement IMPORT FOREIGN SCHEMA that supports Sybase

### PR DESCRIPTION
**Pull request by select-artur**
Hello,

This pull request solves the issue #104.
It seems that there is not schemas in SAP ASE. So `IMPORT FOREIGN SCHEMA` imports tables of specific owner. So for SAP ASE table owner is equal to schema.

If you have notes about this I will fix it.

### CODE REVIEW

**Comment by GeoffMontee** [comment]
Test this, please

**Comment by GeoffMontee** [comment]
Thank you very much for another great PR, @select-artur!

**Comment by select-artur** [comment]
You are welcome! I'm not so familiar with SAP ASE. So I hope that I didn't broke anything.

**Comment by juliogonzalez** [comment]
Retest this please (Jenkins was crashed).

**Pull request merged**
