### PR TITLE
Extend Import Foreign Schema to Views

### LINKED ISSUE #178: FEATURE REQUEST:  Extend Import Foreign Schema to Views
Looking at the source code, importing foreign schema is limited to Tables only.  Please extend it to work with Views as well.   Thank you!

### PR DESCRIPTION
**Pull request by juliogonzalez**
Fixes #178

Replaces #233 as this PR adds tests on top.

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Ok, funny fact: the test passes in all cases except for PostgreSQL 9.4

**Comment by juliogonzalez** [comment]
Ah... of course: https://github.com/tds-fdw/tds_fdw/pull/91#issuecomment-244392844

> IMPORT FOREIGN SCHEMA is only available for PostgreSQL >= 9.5

And for reference in the future: https://www.postgresql.org/docs/9.5/sql-importforeignschema.html (there's no doc for <= 9.5)

**Comment by juliogonzalez** [comment]
Ping @GeoffMontee :-)

**Comment by GeoffMontee** [comment]
Thanks, @juliogonzalez! Sorry for overlooking this one.

**Pull request merged**
