### PR TITLE
Issue #364: Release 2.0.4 to prepare for PostgreSQL 17

### PR DESCRIPTION
**Pull request by GeoffMontee**
See issue #364

### CODE REVIEW

**Comment by GeoffMontee** [comment]
Test this, please

**Comment by GeoffMontee** [comment]
Hi @juliogonzalez,

Are you free to review these changes?

Thanks!

**Review by juliogonzalez — COMMENTED** [review]
Maybe I am wrong, but don't you need to modify https://github.com/tds-fdw/tds_fdw/blob/master/Makefile#L33 as well?

Other than this, rest of the PR LGTM.

**Comment by GeoffMontee** [comment]
Nice catch. Thanks! I fixed that. I will continue prepping the release after Jenkins confirms that my new commit builds.

**Review by juliogonzalez — COMMENTED** [review]
LGTM

**Pull request merged**
