### PR TITLE
Add tests for column matching

### PR DESCRIPTION
**Pull request by juliogonzalez**
Checks for a36cf02, 6d01ba9 and 28b9dcc

Tested and working at https://jenkins.juliogonzalez.es/job/tds_fdw-build-ng/5/

### CODE REVIEW

**Comment by GeoffMontee** [comment]
Thanks for the PR!

For these tests, I think we should also test that we can select a subset of the columns from the table, so we can make sure that the column mapping is working properly with match_column_names on and off. We should probably also check to make sure that we get the value that we are expecting.

So in addition to this query:

```
SELECT * FROM @PSCHEMANAME.column_match_enabled;
```

I think we should test something like this:

```
SELECT (value = 9223372036854775807) AS pass FROM @PSCHEMANAME.column_match_enabled;
```

Do you want to make these changes to the tests?

**Comment by juliogonzalez** [comment]
Test added.

Let me run Jenkins again, just in case.

**Comment by juliogonzalez** [comment]
https://jenkins.juliogonzalez.es/job/tds_fdw-build-ng/6/

Review the code again (I amended the commit), and let me know if you want any other changes.

**Comment by GeoffMontee** [comment]
Looks great! Just merged the commit. Thanks!

**Pull request merged**
