### PR TITLE
Fix import schema with no table check, no tested yet

### PR DESCRIPTION
**Pull request by jcarnu**
Simple fix for no table in schema error found in #219 and #210.  WIP on sys/information_schema extract for columns and views/tables. (will create another branch)

### CODE REVIEW

**Comment by jcarnu** [comment]
Test this please

**Comment by juliogonzalez** [comment]
JFYI: As I added you to the whitelist for the tests, you don't really need to use the magic comment when submitting the PR, when pushing new commits to a PR, or when pushing an amended commit to a PR.

**Comment by juliogonzalez** [comment]
@jcarnu what's the status of the PR?

**Comment by jcarnu** [comment]
Hey, sorry I'm afk at the moment. I'm quite busy till mid December. Hope i
could get time to check it. It's been a while, sorry. End of year are quite
pressured at work here.

**Comment by jcarnu** [comment]
Reading my patch reminds me some things.
Patch is okaye. We do not have any test case. OTOH, is it necessary to test
this ?

>
>

**Comment by juliogonzalez** [comment]
I am not 100%.

If I understand the patch correctly, this is going to provoke a failure, which is not supported right now by the tests scripts (we should probably add it at some point).

If that's the case, I'd say we can merge the PR as it is, but we should open an issue to allow tests that provoke errors and treat them as passed.

**Comment by GeoffMontee** [comment]
> If that's the case, I'd say we can merge the PR as it is, but we should open an issue to allow tests that provoke errors and treat them as passed.

OK, I merged this PR and I created #235 about the missing test.

**Pull request merged**
