### PR TITLE
Test PR for PR builder [DO NOT MERGE!]

### PR DESCRIPTION
**Pull request by juliogonzalez**
Just a Test PR for Jenkins PR Builder.

@GeoffMontee, do not merge this PR as it's just for testing.

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Ok, BOT seems to be working fine as it started running tests for this PR :-)

**Comment by juliogonzalez** [comment]
Fine. Let's try to break the PR :-)

**Comment by juliogonzalez** [comment]
Ok, all comments were being used to trigger tests as long as the comment was being issued by an admin. Changed now to use a trigger.

**Comment by juliogonzalez** [comment]
Checking the trigger...

**Comment by juliogonzalez** [comment]
Retest this please

**Comment by juliogonzalez** [comment]
Testing config again...

**Comment by juliogonzalez** [comment]
And again... The bot should be ignorning my comments unless the passphrase is present.

**Comment by juliogonzalez** [comment]
Test

**Comment by juliogonzalez** [comment]
Test PASSed.

**Comment by juliogonzalez** [comment]
Yeah, cool, no please ignore my comments :-)

**Comment by juliogonzalez** [comment]
Retest this please

**Comment by juliogonzalez** [comment]
Test this please

**Comment by juliogonzalez** [comment]
test this please

**Comment by juliogonzalez** [comment]
test this please

**Comment by juliogonzalez** [comment]
test this please

**Comment by juliogonzalez** [comment]
:-|

**Comment by juliogonzalez** [comment]
Testing...

**Comment by juliogonzalez** [comment]
Test FAILed.

**Comment by juliogonzalez** [comment]
Bot installed

**Comment by juliogonzalez** [comment]
test this please

**Comment by juliogonzalez** [comment]
Test PASSed.

**Comment by juliogonzalez** [comment]
Interesting.... bot is installed but the job still uses my credentials. I just tried reconfiguring the job. If that doesn't work I'll need to reboot Jenkins.

**Comment by juliogonzalez** [comment]
retest this please

**Comment by juliogonzalez** [comment]
retest this please

**Comment by juliogonzalez** [comment]
Much better!

**Comment by juliogonzalez** [comment]
Fine!

@GeoffMontee, could you please trigger the bot to see if your rights are correctly configurd at Jenkins?

Just write a comment with the same content as my last comment before the last "Test passed".

After this I'll test this for "external users". They should be able to run create PRs, but tests shouldn't run automatically. In this case either you or me will issue a comment to trigger tests after reviewing and before merging.

**Comment by GeoffMontee** [comment]
retest this please

**Comment by juliogonzalez** [comment]
Great :-D

Final step is to test a PR from an external user (not a project member). After I confirm that it's working as expected, I'll write a small manual on how to use this, so you can see how it works (maybe you'll even start creating your own PRs :-)

**Comment by GeoffMontee** [comment]
Awesome. Thanks, @juliogonzalez! This PR webhook seems really useful!

**Comment by juliogonzalez** [comment]
Tests are complete. Closing PR.

**Pull request closed without merging**
